export default {
    EVENTS_NEARBY_LOAD: 'EVENTS_NEARBY_LOAD',
    EVENTS_NEARBY_LOAD_SUCCESS: 'EVENTS_NEARBY_LOAD_SUCCESS',
    EVENTS_NEARBY_LOAD_FAILED: 'EVENTS_NEARBY_LOAD_FAILED',
    EVENTS_CATEGORIES_LOAD: 'EVENTS_CATEGORIES_LOAD',
    EVENTS_CATEGORIES_LOAD_SUCCESS: 'EVENTS_CATEGORIES_LOAD_SUCCESS',
    EVENTS_CATEGORIES_LOAD_FAILED: 'EVENTS_CATEGORIES_LOAD_FAILED',

    AUTH_ACCOUNT_KIT: 'AUTH_ACCOUNT_KIT',
    AUTH_ACCOUNT_KIT_SUCCESS: 'AUTH_ACCOUNT_KIT_SUCCESS',
    AUTH_ACCOUNT_KIT_FAILED: 'AUTH_ACCOUNT_KIT_FAILED',

    USER_UPDATE_CATEGORIES: 'USER_UPDATE_CATEGORIES',
    USER_UPDATE_CATEGORIES_SUCCESS: 'USER_UPDATE_CATEGORIES_SUCCESS',
    USER_UPDATE_CATEGORIES_FAILED: 'USER_UPDATE_CATEGORIES_FAILED',
    USER_LOAD_STATS: 'USER_LOAD_STATS',
    USER_LOAD_STATS_SUCCESS: 'USER_LOAD_STATS_SUCCESS',
    USER_LOAD_STATS_FAILED: 'USER_LOAD_STATS_FAILED',
    USER_LOAD_ME: 'USER_LOAD_ME',
    USER_LOAD_ME_SUCCESS: 'USER_LOAD_ME_SUCCESS',
    USER_LOAD_ME_FAILED: 'USER_LOAD_ME_FAILED',

    LOCATION_LOAD_GEOLOCATION: 'LOCATION_LOAD_GEOLOCATION'
};
