export default {
    EVENTS_NEARBY_LOAD: 'EVENTS_NEARBY_LOAD',
    EVENTS_NEARBY_LOAD_SUCCESS: 'EVENTS_NEARBY_LOAD_SUCCESS',
    EVENTS_NEARBY_LOAD_FAILED: 'EVENTS_NEARBY_LOAD_FAILED',
    EVENTS_CATEGORIES_LOAD: 'EVENTS_CATEGORIES_LOAD',
    EVENTS_CATEGORIES_LOAD_SUCCESS: 'EVENTS_CATEGORIES_LOAD_SUCCESS',
    EVENTS_CATEGORIES_LOAD_FAILED: 'EVENTS_CATEGORIES_LOAD_FAILED',
};
